version: "3"

services:
  # refeed-web:
  #   image: refeed-web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #     args:
  #       - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
  #       - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  #       - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
  #       # Temporary
  #       # - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   restart: always
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
  #     - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  #     - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
  #     - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

  #     - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
  #     - ICON_BUCKET_URL=${ICON_BUCKET_URL}
  #     - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
  #     - NEXT_PUBLIC_POSTHOG_HOST={NEXT_PUBLIC_POSTHOG_HOST}
  #   ports:
  #     - 3000:3000
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 20000
  #       hard: 40000
  refeed-backend:
    image: refeed-backend
    build:
      context: ./packages/core/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 4050:4050
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 150000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - IMAGE_ACCOUNT_ID=${IMAGE_ACCOUNT_ID}
      - IMAGE_ACCESS_KEY_ID=${IMAGE_ACCESS_KEY_ID}
      - IMAGE_ACCESS_KEY_SECRET=${IMAGE_ACCESS_KEY_SECRET}
      - IMAGE_BUCKET_URL=${IMAGE_BUCKET_URL}
