[package]
name = "prisma-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
prisma-client-rust-cli = { default-features = false, features = ["postgresql"], git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }